### ISSUE TITLE
pdf renderer placed in different directory from global.properties

### ISSUE THREAD

**Issue by Giuliano69** [jpotts/ansible-alfresco#4]
Hi jpotts
maybe there is a problem in tasks/doInstallPDFRenderer.yml

The pdf renderer is not found:

`2021-02-08 12:56:28,871  ERROR [transform.pdfrenderer.AlfrescoPdfRendererContentTransformerWorker] [main] Legacy Alfresco PDF Renderer is not available for transformations. Execution result:    os:       Linux   command:    /opt/alfresco/common/alfresco-pdf-renderer/alfresco-pdf-renderer --version   succeeded:  false   exit code:  1   out:           err:        Cannot run program "/opt/alfresco/common/alfresco-pdf-renderer/alfresco-pdf-renderer": error=20, Non è una directory`

The template for alfresco.global properties is set to:
```
alfresco-pdf-renderer.root={{ alf_home }}/common/alfresco-pdf-renderer
alfresco-pdf-renderer.exe=${alfresco-pdf-renderer.root}/alfresco-pdf-renderer
```

But the insaller is using a different DEST directory for pdf-rederer (one level higher)

```
- name: Extract PDF Renderer
  unarchive:
    src: '{{ alf_home }}/dist/{{ alf_archive_root_dir }}/alfresco-pdf-renderer/alfresco-pdf-renderer-1.1-linux.tgz'
    dest: '{{ alf_home }}/common'
    copy: no	
```

PROPOSAL: One of the two files should be changed (the task or the properties) accordingly.
